### PR TITLE
Upgrade issue template to Github issue forms

### LINKED ISSUE #20: Upgrade our issue templates to use GitHub issue forms ✍️
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by KKVANONYMOUS**
This PR resolves #20 

I have completed the following tasks:

 - [x] Fork & clone this repository
 - [x] Prepare bug report issue form in .github/ISSUE_TEMPLATE/bug.yaml
 - [x] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml
 - [x] Prepare feature request issue form in .github/ISSUE_TEMPLATE/feature.yaml
 - [x] Push changes to master and test issue forms on your fork
 - [x] Submit pull request
 
@christyjacob4  Please review it and suggest the required changes

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@KKVANONYMOUS Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

**Comment by KKVANONYMOUS** [comment]
> @KKVANONYMOUS Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly. Thank you.

@lohanidamodar 
I have made the required changes
Please review it
Thanks

**Review by lohanidamodar — APPROVED** [review]
Great work @KKVANONYMOUS 🚀

**Comment by christyjacob4** [comment]
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!

**Pull request merged**
