### PR TITLE
added typing declaration

### LINKED ISSUE #3: Missing typescript support
After trying to work with this sdk in a typescript based node.js project i found out that this node.js SDK is missing typescript support.
That might happen because its missing the index.d.ts file we have added to the client SDK a few weeks ago.

### PR DESCRIPTION
**Pull request by privateOmega**
@eldadfux When you migrate these changes to sdk-generator, please lookout for `Promise<Response>` to Promisified Request's Response type.
fixes #3

### CODE REVIEW

**Comment by privateOmega** [comment]
@eldadfux Would be great if you could add `hacktoberfest-accepted` label to this.

**Comment by eldadfux** [comment]
Looks great! I'll work on the generator templates in the coming days, I might want your code-review when I'm ready 🙏🏻

**Comment by eldadfux** [comment]
@privateOmega let me know if you want us to send a you the Appwrite Hacktoberfest swag package. I've also sent you an invite to our Github org, and you can add our badge to your profile.

**Comment by privateOmega** [comment]
> Looks great! I'll work on the generator templates in the coming days, I might want your code-review when I'm ready 🙏🏻

Definitely. I will be happy to.

**Comment by privateOmega** [comment]
> @privateOmega let me know if you want us to send a you the Appwrite Hacktoberfest swag package. I've also sent you an invite to our Github org, and you can add our badge to your profile.

Sure, I would like the swag package. Also thank you so much for the organization invite, it's an honor.

**Comment by TorstenDittmann** [comment]
Alright, we have this now within our SDK. Closing the PR.

**Pull request closed without merging**
